# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  config.ssh.username = "vagrant"
  config.ssh.insert_key = true
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 30000, host: 33333

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  
  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
    vb.memory = "4096"
	vb.cpus = "2"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
	
	yum update
	yum install -y wget
	yum install -y git cmake gcc-c++ java-1.8.0-openjdk-devel systemtap systemtap-sdt-devel bison flex libtool ncurses-devel ant elfutils-libelf-devel rpm-build
	yum install -y vim gdb gdb-gdbserver ctags
	
	# to build c++ 11
	yum --enablerepo=extras install -y centos-release-scl
	yum install -y devtoolset-8-gcc* epel-release
	yum install -y cmake3
	
	cd /home/vagrant
	mkdir -p bin
	ln -sf /usr/bin/cmake3 /home/vagrant/bin/cmake
	chown -R vagrant /home/vagrant/bin
	echo 'export PATH=/home/vagrant/bin:$PATH' >> /home/vagrant/.bashrc
	echo 'source scl_source enable devtoolset-8' >> /home/vagrant/.bash_profile
	
	# configure astyle
	if [ ! -d /home/vagrant/astyle-install]; then
		cd /home/vagrant
		mkdir astyle-install
		cd astyle-install
		wget https://jaist.dl.sourceforge.net/project/astyle/astyle/astyle%203.1/astyle_3.1_linux.tar.gz -O astyle.tar.gz
		tar -xzf astyle.tar.gz
		cd astyle
		cmake .
		make
		make install
	fi
	
	mkdir -p /home/vagrant/.git/hooks
	cd /home/vagrant/.git/hooks
	wget https://github.com/hgryoo/cubrid-vagrant-dev/raw/master/shell/pre-commit
	chmod +x pre-commit
	chown vagrant pre-commit
	
	cd /home/vagrant/bin
	wget https://github.com/hgryoo/cubrid-vagrant-dev/raw/master/shell/indent
	chmod +x indent
	chown vagrant indent
	
	git config --global hooks.indent /home/vagrant/bin/indent
	
	cd /home/vagrant
	
	if [ ! -d cubrid ]; then
		# git clone --recurse-submodules https://github.com/cubrid/cubrid.git cubrid
		git clone https://github.com/cubrid/cubrid.git cubrid
		chown -R vagrant cubrid
	fi
	  
	if [ ! -d myenv ]; then
		git clone https://github.com/hgryoo/MyCentOSEnv myenv
		chown -R vagrant myenv
	fi
  SHELL
end
